version: "3.9"

services:
  payment-db:
    image: postgres:13
    container_name: payment-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: POSTGRES
      POSTGRES_PASSWORD: POSTGRES
      POSTGRES_DB: paymentdb
    volumes:
      - local_postgres_payment_db:/var/lib/postgresql/data

  payment-service:
    container_name: payment-service
    image: payment-db-service
    build: ./
    ports:
      - "8082:8082"
    depends_on:
      - payment-db

volumes:
  local_postgres_payment_db: